<?php
// php array function 
$first_array = array(1, 2, 3, 4, 5);
echo $first_array[0];
echo "<br>";
$fruits = array("apple", "banana", "orange", "grape");
array_pop($fruits);
echo "<pre>";
echo print_r($fruits);
echo "</pre>";
echo "<br>";
array_push($fruits, "mango");
echo "<pre>";
echo print_r($fruits);
echo "</pre>";
echo "<br>";
array_shift($fruits);
echo "<pre>";
echo print_r($fruits);
echo "</pre>";
echo "<br>";
array_unshift($fruits, "kiwi");
echo "<pre>";
echo print_r($fruits);
echo "</pre>";
echo "<br>";
array_splice($fruits, 1, 0, "pineapple");
echo "<pre>";
echo print_r($fruits);
echo "</pre>";
echo "<br>";
array_splice($fruits, 1, 1, "mango");
echo "<pre>";
echo print_r($fruits);
echo "</pre>";
echo "<br>";
$numbers = array(1, 2, 3, 4, 5);
echo count($numbers);
echo "<br>";
$array_rsort = array("a", "b", "c", "d", "e");
rsort($array_rsort);
echo "<pre>";
echo print_r($array_rsort);
echo "</pre>";
echo "<br>";
$array_sort = array("a", "b", "c", "d", "e");
sort($array_sort);
echo "<pre>";
echo print_r($array_sort);
echo "</pre>";
echo "<br>";
$array_reverse = array("a", "b", "c", "d", "e");
$array_reverse = array_reverse($array_reverse);
echo "<pre>";
echo print_r($array_reverse);
echo "</pre>";
echo "<br>";
$array_unique = array("a", "b", "c", "d", "e", "a", "b", "c", "d", "e");
$array_unique = array_unique($array_unique);
echo "<pre>";
echo print_r($array_unique);
echo "</pre>";
echo "<br>";
$array_merge = array("a", "b", "c", "d", "e");
$array_merge = array_merge($array_merge, $array_unique);
echo "<pre>";
echo print_r($array_merge);
echo "</pre>";
echo "<br>";
$array_merge_recursive = array("a", "b", "c", "d", "e");
$array_merge_recursive = array_merge_recursive($array_merge_recursive, $array_unique);
echo "<pre>";
echo print_r($array_merge_recursive);
echo "</pre>";
echo "<br>";
$quotes = array("I said, \"I'm not crazy.\"", "I said, \"I'm not crazy.\"");

    foreach ($quotes as $value) {
        echo $value . "<br>";
    }
echo "<br>";
echo implode(" ", $quotes);
echo "<br>";
$exploads = explode(" ", "I said, \"I'm not crazy.\"");
echo "<pre>";
echo print_r($exploads);
echo "</pre>";

echo "<br>";
$texts = "I miss you ever";
print_r(explode(" ", $texts));